# This file was *autogenerated* from the file shifted_maze.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
load("shifted_space_translator.sage")
load("maze_generator.sage")

class ShiftedMaze(object):
    def __init__(
            self, x,y, height=_sage_const_3 , level=_sage_const_3 , corridor=_sage_const_3 , lang="red",
            floors = [[ShiftedFirstFloor], [ShiftedSecondFloor], [ShiftedThirdFloor]], 
            glasses =[[ShiftedFenceOne, ShiftedGlassOne, ShiftedGlassTwo]], 
            walls = [[ShiftedWallFirstOne, ShiftedWallFirstTwo, ShiftedWallFirstThree], [ShiftedWallSecondOne, ShiftedWallSecondTwo, ShiftedWallSecondThree], [ShiftedWallThirdOne, ShiftedWallThirdTwo, ShiftedWallThirdThree]]):
        self.M=[]
        self.T=[]
        self._lang=[]
        F,G,W = map(len,(floors,glasses,walls))
        offset=vector((_sage_const_1 ,_sage_const_0 ,_sage_const_1 ))
        h=vector((_sage_const_0 ,height+_sage_const_1 ,_sage_const_0 ))
        for f in range(level):
            M=MazeTree(x,y)
            ff,gg,ww = map(lambda t:f%t, (F,G,W))
            ceiling = f==level-_sage_const_1 
            T=ShiftedSpaceTranslator(M.maze,height=height, corridor=corridor, ceiling=ceiling, offset=offset+f*h, floors=floors[ff], glasses=glasses[gg], walls=walls[ww])
            self.M += [M]
            self.T += [T]
            if lang == "mc":
                self._lang += [T.mc()]
            elif lang == "slow_red":
                self._lang += [T.red_dust()]
            else:
                self._lang += [T.fast_red_dust()]

    def lang(self):
        return "\n".join(self._lang)

